config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles #, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  get 'signup',to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user #to associate the articals to the User
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 20, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }
  has_many :articles #to associate the User to many articles
  validates :username,  presence: true,  
                        uniqueness: { case_sensitive: false }, 
                        length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX =   /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i                
  validates :email,     presence: true,  
                        uniqueness: { case_sensitive: false }, 
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 5)

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      @article.user = User.first
      flash[:notice] = "Article was successfully updated."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:notice] = "Article was successfully deleted."
      redirect_to articles_path

    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.paginate(page: params[:page], per_page: 3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you have successfully signed up!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account information was successfully updated!"
      redirect_to user_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    @articles = @user.articles.paginate(page: params[:page], per_page: 5)
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def gravatar_for(user,options = {size: 80})
    # include MD5 gem, should be part of standard ruby install
    # require 'digest/md5'

    # get the email from URL-parameters or what have you and make lowercase
    email_address = user.email.downcase

    # create the md5 hash
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    # compile URL which can be used in <img src="RIGHT_HERE"...
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block mt-3")
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <% @articles.each do |article| %>
                <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
                    <div class="card-header fst-italic">
                        <% if article.user %>
                            by <%= link_to article.user.username, user_path(article.user) %>
                        <% end %>
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            <%= link_to article.title, article_path(article), class: "text-success" %>
                        </h5>
                        <p class="card-text"><%= truncate(article.description, length:100) %></p>
                        <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
                        <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
                        <%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                    </div>
                    
                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(article.created_at) %> ago, updated <%= time_ago_in_words(article.updated_at) %> ago</small>
                    </div>
                </div>
            <% end %>
            
        </div>
    </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @article %>
            <%= form_with(model: @article, class: "shadow p-3 mb-5 bg-info rounded", local: true) do |form|%>

                <div class="form-group row">
                    <%= form.label :title, class: "col-sm-2 col-form-label" %>
                    
                    <div class="col-sm-10">
                        <%= form.text_field :title, class:"form-control shadow rounded mb-3", placeholder: "Title of the article ..." %>
                    </div>
                </div>
                <div class="form-group row">
                <%= form.label :description, class: "col-sm-2 col-form-label" %>
                    <div class="col-sm-10">
                        <%= form.text_area :description, rows:10, class: "form-control shadow rounded mb-3", placeholder: "Description of the article ..."%>
                    </div>
                </div>

                <div class="form-group d-flex justify-content-center">
                    <%= form.submit class: "btn btn-outline-light" %>
                </div>

            <% end %>
            <div class="mb-3 text-center">
                <%= link_to '[ Back to the articles listings ]', articles_path, class: "text-center"%>
            </div>
        </div>
    </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-4">Edit the article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-4">All Articles</h1>

<div class="flicker_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flicker_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center mt-4">Create a new article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
    <h2 class="text-center mt-4"><%= @article.title %> </h2>
    <div class="row justify-content-center">
        <div class="col-8">
            <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
                <div class="card-header fst-italic">
                    by <%= @article.user.username %>
                    <%= link_to gravatar_for(@article.user), @article.user %>
                </div>
                <div class="card-body">
                    <div class="card-text text-start"><%= simple_format(@article.description) %></div>
                        <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
                    <%= link_to "Delete", article_path(@article), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-outline-danger" %>
                </div>
                <div class="card-footer text-muted">
                    <small>Created <%= time_ago_in_words(@article.created_at) %> ago, updated <%= time_ago_in_words(@article.updated_at) %> ago</small>
                </div>


                
            </div>
        </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
    <div class="container text-center text-white">
        <small>Copyright &copy; <%= link_to 'Dany Weis', "https://danyweis.com", class: "text-white" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, message| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <%= message %>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <%= link_to 'alpha blog', root_path, class: "navbar-brand", id: "logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to 'Bloggers', users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Articles
                    </a>
                    <ul class="dropdown-menu">
                        
                        <%= link_to 'Create a new article', new_article_path, class: "dropdown-item" %>
                        <%= link_to 'All articles', articles_path, class: "dropdown-item" %>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation'%>
    <div id="page-content">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
    <%= render 'layouts/footer' %>


    
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>

<%= link_to 'Go to the articles listing', articles_path %> | 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <div class="jumbotron text-center text-white">
        <h1 class="display-4">Alpha Blog</h1>
        <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
        <hr class="my-4">
        <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
        <%= link_to 'Sign up!', signup_path, class: 'btn btn-success btn-lg', role: 'button' %>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved:</h4>
        <ul>
            <% obj.errors.full_messages.each do |message|%>
                <li>
                    <%= message%> 
                </li>
            <% end %>
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col-10">
            <%= render 'shared/errors', obj: @user %>
            <%= form_with(model: @user, class: "shadow p-3 mb-5 bg-info rounded", local: true) do |form|%>

                <div class="form-group row">
                    <%= form.label :username, class: "col-sm-2 col-form-label" %>
                    
                    <div class="col-sm-10">
                        <%= form.text_field :username, class:"form-control shadow rounded mb-3", placeholder: "JohnDoe" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :email, class: "col-sm-2 col-form-label" %>
                    
                    <div class="col-sm-10">
                        <%= form.email_field :email, class:"form-control shadow rounded mb-3", placeholder: "johndoe@email.com" %>
                    </div>
                </div>

                <div class="form-group row">
                    <%= form.label :password, class: "col-sm-2 col-form-label" %>
                    
                    <div class="col-sm-10">
                        <%= form.password_field :password, class:"form-control shadow rounded mb-3", placeholder: "Choose a password" %>
                    </div>
                </div>

                <div class="form-group d-flex justify-content-center">
                    <%= form.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light") %>
                </div>

            <% end %>
            <div class="mb-3 text-center">
                <%= link_to '[ Back to the articles listings ]', articles_path, class: "text-center"%>
            </div>
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-4">Edit your profile informarion</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-4">Alpa bloggers</h1>

<div class="flicker_pagination">
    <%= will_paginate @users, :container => false %>
</div>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-8">
            <% @users.each do |user| %>
                <div class="card text-center mt-4 shadow mb-5 bg-white rounded">
                    <div class="card-header fst-italic">
                        <%= link_to user.username , user_path(user)%>
                    </div>
                    <div class="card-body">
                        <%= link_to gravatar_for(user, size: 150), user %>
                        
                        <p class="card-text"><%= pluralize(user.articles.count, "article") %> </p>
                        <%= link_to "View profile", user, class: "btn btn-outline-success" %>
                        <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %> 
                    </div>
                    <div class="card-footer text-muted">
                        <small>Joined <%= time_ago_in_words(user.created_at) %> ago </small> 
                    </div>
                </div>
            <% end %>
            
        </div>
    </div>
</div>

<div class="flicker_pagination mb-4">
    <%= will_paginate @users, :container => false %>
</div>

app/views/users/new.html.erb
<h1 class="text-center mt-4">Sign up for Alpha-Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>

<%= gravatar_for @user, size: 200 %>
<div class="text-center mt-4">
    <%= link_to 'Edit your profile', edit_user_path, class: "btn btn-outline-info" %>
</div>

<h3 class="text-center mt-4">Articles</h3>

<div class="flicker_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flicker_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>